export interface Participant {
  socketId: string;
  username: string;
  isMuted: boolean;
  isHandRaised: boolean;
  isHost: boolean;
}

export interface ChatMessage {
  id: string;
  socketId: string;
  username: string;
  text: string;
  textBn?: string;
  timestamp: number;
  type: "user" | "system";
}

export type Language = "en" | "bn";

export const translations = {
  en: {
    title: "Surokkha আড্ডা",
    tagline: "High-quality, lightweight voice group chat with live translation, host controls, and lightning-fast WebRTC audio.",
    createRoom: "Create a New Room",
    joinRoom: "Join an Existing Room",
    roomNamePlaceholder: "Enter Room Code (e.g., chill-vibes)",
    usernamePlaceholder: "Enter your nickname",
    joinBtn: "Join Conversation",
    createBtn: "Create Room",
    leaveBtn: "Leave Room",
    muteMic: "Mute Mic",
    unmuteMic: "Unmute Mic",
    raiseHand: "Raise Hand",
    lowerHand: "Lower Hand",
    chatTab: "Live Chat",
    participantsTab: "Participants",
    hostControls: "Host Controls",
    kickUser: "Kick Peer",
    mutePeer: "Mute Peer",
    unmutePeer: "Unmute Peer",
    lowerPeerHand: "Lower Peer Hand",
    chatInputPlaceholder: "Type a message...",
    send: "Send",
    copyLink: "Copy Invite Link",
    copied: "Copied!",
    noParticipants: "No other participants in this room yet.",
    hostTag: "Host",
    youTag: "You",
    roomCode: "Room Code",
    roomPassword: "Room Password (Optional)",
    roomPasswordPlaceholder: "Leave blank for no password",
    enterPasswordToJoin: "Enter Room Password",
    passwordRequired: "This room is password-protected. Please enter the correct password to join.",
    incorrectPassword: "Incorrect password. Access denied.",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    recordingStarted: "Recording started. All room audio is being mixed and recorded locally.",
    recordingStopped: "Recording stopped. Your audio file is ready for download.",
    recordingSaving: "Saving recording...",
    errorMicRequired: "Microphone permission is strictly required for this voice-only chat app.",
    roomEnded: "You have left the conversation.",
    kickedMsg: "You were removed from the room by the host.",
    forceMutedMsg: "The host has muted your microphone.",
    system: "System",
    welcomeTitle: "Welcome to Surokkha আড্ডা 🎤",
    bengaliSupport: "বাংলা ভাষা সমর্থন",
    aboutTitle: "Bilingual WebRTC Voice Chat",
    voiceChatting: "Active Voice Chatting",
    handRaised: "Raised hand",
    backToHome: "Back to Home",
    connectionStatus: "Connection",
    connected: "Connected",
    disconnected: "Disconnected",
    reconnecting: "Reconnecting...",
    activeSpeakers: "Active Speakers",
    roomCapacity: "10-20 user-capacity voice room over lightweight Peer-to-Peer WebRTC mesh.",
    bengaliHelpText: "এই ভয়েস চ্যাট অ্যাপটি সম্পূর্ণ নিরাপদ এবং রিয়েল-টাইম WebRTC প্রযুক্তি দ্বারা পরিচালিত।",
  },
  bn: {
    title: "সুরক্ষা আড্ডা",
    tagline: "লাইভ ট্রান্সলেশন, হোস্ট কন্ট্রোল এবং দ্রুতগতির WebRTC অডিও সহ প্রিমিয়াম ভয়েস গ্রুপ চ্যাট রুম।",
    createRoom: "নতুন রুম তৈরি করুন",
    joinRoom: "বিদ্যমান রুমে যুক্ত হোন",
    roomNamePlaceholder: "রুমের কোড দিন (যেমন: আড্ডা-রুম)",
    usernamePlaceholder: "আপনার ডাকনাম লিখুন",
    joinBtn: "আড্ডায় যোগ দিন",
    createBtn: "রুম তৈরি করুন",
    leaveBtn: "আড্ডা ত্যাগ করুন",
    muteMic: "মিউট করুন",
    unmuteMic: "আনমিউট করুন",
    raiseHand: "হাত তুলুন (Raise Hand)",
    lowerHand: "হাত নামান",
    chatTab: "লাইভ চ্যাট",
    participantsTab: "অংশগ্রহণকারী",
    hostControls: "হোস্ট কন্ট্রোল",
    kickUser: "বের করে দিন",
    mutePeer: "মিউট করুন",
    unmutePeer: "আনমিউট করুন",
    lowerPeerHand: "হাত নামিয়ে দিন",
    chatInputPlaceholder: "বার্তা লিখুন...",
    send: "পাঠান",
    copyLink: "ইনভাইট লিঙ্ক কপি করুন",
    copied: "কপি হয়েছে!",
    noParticipants: "এই রুমে এখনও অন্য কোনো অংশগ্রহণকারী নেই।",
    hostTag: "হোস্ট",
    youTag: "আপনি",
    roomCode: "রুমের কোড",
    roomPassword: "রুমের পাসওয়ার্ড (ঐচ্ছিক)",
    roomPasswordPlaceholder: "পাসওয়ার্ড না দিলে খালি রাখুন",
    enterPasswordToJoin: "রুমের পাসওয়ার্ড লিখুন",
    passwordRequired: "এই রুমটি পাসওয়ার্ড দ্বারা সুরক্ষিত। যোগ দিতে সঠিক পাসওয়ার্ডটি লিখুন।",
    incorrectPassword: "ভুল পাসওয়ার্ড। রুমে প্রবেশ করার অনুমতি নেই।",
    startRecording: "রেকর্ডিং শুরু করুন",
    stopRecording: "রেকর্ডিং বন্ধ করুন",
    recordingStarted: "রেকর্ডিং শুরু হয়েছে। সবার অডিও মিক্স করে রেকর্ড করা হচ্ছে।",
    recordingStopped: "রেকর্ডিং বন্ধ হয়েছে। আপনার ফাইলটি ডাউনলোডের জন্য প্রস্তুত।",
    recordingSaving: "রেকর্ডিং ফাইল তৈরি হচ্ছে...",
    errorMicRequired: "এই ভয়েস চ্যাট অ্যাপটির জন্য মাইক্রোফোনের অনুমতি অবশ্যই প্রয়োজন।",
    roomEnded: "আপনি আড্ডা ত্যাগ করেছেন।",
    kickedMsg: "আপনাকে হোস্ট রুম থেকে বের করে দিয়েছেন।",
    forceMutedMsg: "হোস্ট আপনাকে মিউট করে দিয়েছেন।",
    system: "সিস্টেম",
    welcomeTitle: "সুরক্ষা আড্ডায় আপনাকে স্বাগতম 🎤",
    bengaliSupport: "বাংলা ভাষা সমর্থন",
    aboutTitle: "দ্বিভাষিক WebRTC ভয়েস চ্যাট",
    voiceChatting: "সক্রিয় ভয়েস চ্যাট",
    handRaised: "হাত তুলেছেন",
    backToHome: "হোমে ফিরে যান",
    connectionStatus: "সংযোগ",
    connected: "সংযুক্ত",
    disconnected: "সংযোগ বিচ্ছিন্ন",
    reconnecting: "পুনরায় সংযোগ করা হচ্ছে...",
    activeSpeakers: "সক্রিয় বক্তা",
    roomCapacity: "হালকা পিয়ার-টু-পিয়ার WebRTC মেশের মাধ্যমে ১০-২০ জনের ভয়েস রুম সুবিধা।",
    bengaliHelpText: "এই ভয়েস চ্যাট অ্যাপটি সম্পূর্ণ নিরাপদ এবং রিয়েল-টাইম WebRTC প্রযুক্তি দ্বারা পরিচালিত।",
  },
};
